# Generated by Django 2.0.3 on 2018-06-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='知名机构', max_length=10, verbose_name='机构标签'),
        ),
    ]
