# Generated by Django 2.0.3 on 2018-05-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_video_learn_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='', max_length=300, verbose_name='老师告诉你'),
        ),
        migrations.AddField(
            model_name='course',
            name='youneed_know',
            field=models.CharField(default='', max_length=300, verbose_name='课程须知'),
        ),
    ]
